[package]
name = "pr47"
version = "0.1.0"
authors = ["ICEY <icey@icey.tech>"]
edition = "2018"
description = "A semi-experimental programming language. Still working in progress."
readme = "README.md"
repository = "https://github.com/pr47/project-47"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
paste = "1.0"
memoffset = "0.5"
unchecked_unwrap = "2.0.2"
smallvec = "1.4.2"
pr47-codegen = { path = "../pr47-codegen" }

[features]
default = ["optimized-rtlc"]

async = []
no-rtlc = []
optimized-rtlc = []
afterburn = []
specialization = []
