[package]
name = "pr47-codegen"
version = "0.0.2"
authors = ["ICEY <icey@icey.tech>"]
edition = "2018"
description = "procedural macro crate for Pr47. not ready yet."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1", features = ["full"] }
